### ISSUE TITLE
When event is unsaved, the events request fails

### ISSUE THREAD

**Issue by bobbywilson0** [therabidbanana/eventbrite#1]
Had an unsaved event in eventbright then when the api request is made through the eventbright library it fails with this error: NoMethodError: undefined method `num_attendee_rows=' for #EventBright::Event:0x10174ba10

**Comment by therabidbanana** [comment]
Fixing undocumented field num_attendee_rows. Closed by c41d0f65657ae4f92b45c9468abc9b7db27102c7.

**Comment by therabidbanana** [comment]
Thanks for bringing this to my attention. The Eventbrite API documentation is somewhat shoddy, and apparently they decided to add new fields without documenting them.
