### ISSUE TITLE
init_with_hash throws error every time Eventbrite changes their api

### ISSUE THREAD

**Issue by lancejpollard** [therabidbanana/eventbrite#2]
Maybe you could add in there an `unless self.respond_to?(key)`, so if eventbrite changes their api before you get a chance to update your gem, it won't throw errors in production.

Best,
Lance

**Comment by therabidbanana** [comment]
Been meaning to do this for a while. Thanks for reminding me. 

init_with_hash shouldn't try to use invalid keys [Closed by 9dbc22a7ff92b18a7052c3d1d392b78c9f032f34]

**Comment by lancejpollard** [comment]
thanks!
