### ISSUE TITLE
default API key has been hijacked by a spammer - we may need to disable it...

### ISSUE THREAD

**Issue by ryanj** [therabidbanana/eventbrite#7]
Hi David,
Our team has informed me that a spammer may have hijacked your default developer key - 
https://github.com/therabidbanana/eventbrite/blob/master/lib/eventbrite/main.rb

Attempting to give you some advanced notice in case we need to disable it!
Best,
--Ryan Jarvinen
Developer Advocate - Eventbrite
@EventbirteAPI

**Comment by therabidbanana** [comment]
Okay - thanks for the heads up! I haven't been using the gem at all, and when I did I registered separate keys. This key was mainly for debugging.

**Comment by ryanj** [comment]
I figured as much. I just wanted to make sure that it didn't look like we were trying to make a competitive move against your client lib.
Thanks for the doc update!

If you get any complaints regarding loss of access via your default key, feel free to refer folks to api@eventbrite.com
