### ISSUE TITLE
`eventbrite` gem

### ISSUE THREAD

**Issue by sssionggg** [therabidbanana/eventbrite#8]
i am not sure that you are still supporting this gem.  since eventbrite is already testing their [new API](http://developer.eventbrite.com/docs/), the old API might not be longer working.

actually, i created a new gem here: https://github.com/OutrageousLabs/eventbrite

there are still some work that needs to be done.  but, i am wondering whether we can work together to make the 1.0.0 release of your gem with my gem.

cheers!  :)

**Comment by therabidbanana** [comment]
I'd be happy to transfer the name to you - as mentioned in the readme, I no longer have any interest in maintaining this. Hopefully their new API is not as painful to work with.

**Comment by lg** [comment]
hi @therabidbanana, sure we'd be happy to take over the name. let us know when you've relinquished it and we'll update our gem. thanks!

**Comment by therabidbanana** [comment]
Should in theory be available if I read the docs right - all versions yanked under the eventbrite name.

**Comment by lg** [comment]
all is set up. thank you so much! <3
